### PR TITLE
Added closing tag to anchor for glyphicon.

### PR DESCRIPTION
**Pull request by rmassoth**
Added a closing tag for the glyphicon link in sort_th_frag.html. The missing tag was causing the browser to render three links instead of one.

### CODE REVIEW

**Review by staticdev — APPROVED** [review]

**Comment by staticdev** [comment]
@rmassoth I saw we have a problem with safety here. Could you run a `poetry update` from your branch and commit the poetry.lock in this branch?

**Comment by rmassoth** [comment]
I ran `poetry update` and ran nox locally but it's still failing safety for nox-poetry. It looks like nox-poetry is set to install exactly version 0.7.1 in the pyproject.toml file. Safety is complaining about versions lower than 0.8.2. Would it be safe to update the version or is there a reason to keep this specific version?

**Comment by staticdev** [comment]
@rmassoth this is another bug and I think nox-poetry can be safely removed from pypoetry.toml actually.

I use this "template" for many projects now, one example of other package I still maintain is this one: https://github.com/staticdev/human-readable you can see I removed it.

**Comment by staticdev** [comment]
@rmassoth I fixed the security problem, please rebase the PR and it will work.

**Comment by rmassoth** [comment]
I rebased and merged my branch. Hopefully everything is good now. Thanks for your help!

**Pull request merged**
